kind: pipeline
type: docker
name: default

steps:

- name: build
  image: lorisleiva/laravel-docker
  commands:
  - node -v
  - npm -v
  - npm ci
  - npm run build

- name: test
  image: lorisleiva/laravel-docker
  commands:
  - npm run test

- name: npm
  image: plugins/npm
  settings:
    username:
      from_secret: npm_username
    password:
      from_secret: npm_password
    email:
      from_secret: npm_email
    token:
      from_secret: npm_token
  when:
    event:
    - tag